name: Analyze and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 19
          distribution: 'temurin'
#
#      - name: Run lint analysis
#        run: ./gradlew lintDebug --stacktrace
#
#      - name: Run detekt (if configured)
#        run: ./gradlew detekt --stacktrace
#
#      - name: Archive lint results
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: lint-results
#          path: app/build/reports/lint-results-debug.html
#
#  test:
#    name: Run Tests
#    runs-on: ubuntu-latest
#    needs: analyze  # Run tests only after analysis passes
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'temurin'
#
#      - name: Run unit tests
#        run: ./gradlew testDebugUnitTest --stacktrace
#
#      - name: Run instrumented tests
#        if: success()
#        run: |
#          # Start emulator (optional - only needed for UI tests)
#          echo "Starting emulator..."
#          ./gradlew connectedDebugAndroidTest --stacktrace
#        env:
#          JAVA_OPTS: "-Xmx4096m"  # Increase memory if needed
#
#      - name: Archive test results
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: test-results
#          path: |
#            app/build/reports/tests/
#            app/build/outputs/androidTest-results/